openapi: 3.0.0
info:
  title: Error Management
  description: >-
    A project for centralizing error handling in an application by using a middleware. The middleware will receive all errors thrown by the application, return a custom error message along with a relevant HTTP status code, and assign a default internal server error (HTTP 500) with a custom message if any of the errors go unhandled.


    This system helps to provide consistent, structured, and comprehensive error handling in the application.
  contact:
    name: Muhammad Ahmed Villa Khan
    url: https://www.linkedin.com/in/muhammad-ahmed-379872126/
    email: m.ahmedk287@gmail.com
  version: '1.0'
servers:
- url: http://localhost:3000/api/v1/errormanagement
  variables: {}
paths:
  /badrequest:
    get:
      tags:
      - Misc
      summary: Bad Request
      description: BAD REQUEST exception is thrown and handled by the middleware that converts the error to a customized message depending on the error code.
      operationId: BadRequest
      parameters: []
      responses:
        '400':
          description: Bad Request
          headers:
            X-Powered-By:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Express
            Content-Length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '98'
            ETag:
              content:
                text/plain:
                  schema:
                    type: string
                  example: W/"62-BLkn+Ap1A2QDvlJ0CjNUrqrspHg"
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Wed, 01 Feb 2023 17:48:56 GMT
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Keep-Alive:
              content:
                text/plain:
                  schema:
                    type: string
                  example: timeout=5
          content:
            application/json; charset=utf-8:
              schema:
                allOf:
                - $ref: '#/components/schemas/BadRequestSampleResponse1'
                - example:
                    message: Missing required parameters, invalid data types, or incorrect syntax in the request.
              example:
                message: Missing required parameters, invalid data types, or incorrect syntax in the request.
      deprecated: false
      security: []
  /forbidden:
    get:
      tags:
      - Misc
      summary: Forbidden
      description: FORBIDDEN exception is thrown and handled by the middleware that converts the error to a customized message depending on the error code.
      operationId: Forbidden
      parameters: []
      responses:
        '403':
          description: Forbidden
          headers:
            X-Powered-By:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Express
            Content-Length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '69'
            ETag:
              content:
                text/plain:
                  schema:
                    type: string
                  example: W/"45-W2E6IR1615WTltvvYUC2PwYqwA4"
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Wed, 01 Feb 2023 17:48:30 GMT
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Keep-Alive:
              content:
                text/plain:
                  schema:
                    type: string
                  example: timeout=5
          content:
            application/json; charset=utf-8:
              schema:
                allOf:
                - $ref: '#/components/schemas/ForbiddenSampleResponse1'
                - example:
                    message: You are not authorized to access the requested resource
              example:
                message: You are not authorized to access the requested resource
      deprecated: false
      security: []
  /notfound:
    get:
      tags:
      - Misc
      summary: Not Found
      description: NOT FOUND exception is thrown and handled by the middleware that converts the error to a customized message depending on the error code.
      operationId: NotFound
      parameters: []
      responses:
        '404':
          description: Not Found
          headers:
            X-Powered-By:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Express
            Content-Length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '140'
            ETag:
              content:
                text/plain:
                  schema:
                    type: string
                  example: W/"8c-2r8H1lRee8vrNM14FrQ53uqQjq4"
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Wed, 01 Feb 2023 17:48:04 GMT
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Keep-Alive:
              content:
                text/plain:
                  schema:
                    type: string
                  example: timeout=5
          content:
            application/json; charset=utf-8:
              schema:
                allOf:
                - $ref: '#/components/schemas/NotFound1'
                - example:
                    message: Unable to locate the requested resource, either because it doesn't exist, or because the URL that the client used is incorrect
              example:
                message: Unable to locate the requested resource, either because it doesn't exist, or because the URL that the client used is incorrect
      deprecated: false
      security: []
  /unauthorized:
    get:
      tags:
      - Misc
      summary: Unauthorized
      description: UNAUTHORIZED exception is thrown and handled by the middleware that converts the error to a customized message depending on the error code.
      operationId: Unauthorized
      parameters: []
      responses:
        '401':
          description: Unauthorized
          headers:
            X-Powered-By:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Express
            Content-Length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '124'
            ETag:
              content:
                text/plain:
                  schema:
                    type: string
                  example: W/"7c-XKCWfV4pI3WT1LnoYfIg0E//H8c"
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Wed, 01 Feb 2023 17:47:38 GMT
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: keep-alive
            Keep-Alive:
              content:
                text/plain:
                  schema:
                    type: string
                  example: timeout=5
          content:
            application/json; charset=utf-8:
              schema:
                allOf:
                - $ref: '#/components/schemas/UnauthorizedSampleResponse1'
                - example:
                    message: Please provide a valid username and password or other form of authentication to access the requested resource.
              example:
                message: Please provide a valid username and password or other form of authentication to access the requested resource.
      deprecated: false
      security: []
components:
  schemas:
    BadRequestSampleResponse1:
      title: BadRequestSampleResponse1
      required:
      - message
      type: object
      properties:
        message:
          type: string
      example:
        message: Missing required parameters, invalid data types, or incorrect syntax in the request.
    ForbiddenSampleResponse1:
      title: ForbiddenSampleResponse1
      required:
      - message
      type: object
      properties:
        message:
          type: string
      example:
        message: You are not authorized to access the requested resource
    NotFound1:
      title: NotFound1
      required:
      - message
      type: object
      properties:
        message:
          type: string
      example:
        message: Unable to locate the requested resource, either because it doesn't exist, or because the URL that the client used is incorrect
    UnauthorizedSampleResponse1:
      title: UnauthorizedSampleResponse1
      required:
      - message
      type: object
      properties:
        message:
          type: string
      example:
        message: Please provide a valid username and password or other form of authentication to access the requested resource.
tags:
- name: Misc
  description: ''